name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'gradle'
      - name: Check
        run: gradle check --no-daemon
