name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'corretto'
          java-version: '17'
          # cache: 'gradle'
      - name: Build
        run: ./gradlew build --no-daemon
      - name: Test
        run: ./gradlew test --no-daemon
